from __future__ import annotations

import json
import tempfile
import unittest
from pathlib import Path

from harnessctl.core.factory import generate_harness
from harnessctl.core.vault import load_vault, materialize_vault


class TechIdentityTests(unittest.TestCase):
    """Validate that the Base Harness does not leak its own technology identity
    into Dedicated Harnesses for non-Go projects."""

    def setUp(self):
        self.base_root = Path(__file__).resolve().parents[1]
        self.vault_root = self.base_root / "vault"

    # ── 1. Go Dedicated Harness still has Go references ──────────────────

    def test_go_harness_may_contain_go_references(self):
        """A Go-targeted Dedicated Harness may reference Go skills."""
        profile = self._go_profile()
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            profile_path = root / "profile.json"
            output = root / "project"
            profile_path.write_text(json.dumps(profile), encoding="utf-8")
            result = generate_harness(profile_path, "0.1.0", output)
            self.assertTrue(result["valid"])

    # ── 2. Kotlin/Android Dedicated Harness has no Go dependency ─────────

    def test_kotlin_harness_no_go_semantic_dependency(self):
        """A Kotlin/Android Dedicated Harness must not expose Go identity."""
        profile = self._kotlin_profile()
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            out = self._generate(profile, root)
            self._assert_no_go_identity(out)

    # ── 3. Python Dedicated Harness has no Go dependency ────────────────

    def test_python_harness_no_go_semantic_dependency(self):
        """A Python Dedicated Harness must not expose Go identity."""
        profile = self._python_profile()
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            out = self._generate(profile, root)
            self._assert_no_go_identity(out)

    # ── 4. Agents in vault are self-descriptive ─────────────────────────

    def test_vault_agents_self_descriptive(self):
        """Agent descriptions in vault must not rely on Base tech identity."""
        notes = load_vault(self.vault_root)
        agents = notes.get("agents")
        self.assertIsNotNone(agents)
        # Engineer role should not be described as "Go Engineer"
        self.assertNotIn("Go Engineer", agents.body)
        self.assertIn("Engineer", agents.body)

    # ── 5. Skills not described as "adapted from Go" ────────────────────

    def test_skills_not_adapted_from_go(self):
        """Specialized skills in vault must not describe themselves as adapted from Go."""
        notes = load_vault(self.vault_root)
        skills = notes.get("skills")
        self.assertIsNotNone(skills)
        body_lower = skills.body.lower()
        self.assertNotIn("adapted from go", body_lower)

    # ── 6. Factory README does not assume Base stack ────────────────────

    def test_factory_readme_does_not_presume_base_stack(self):
        """The README generated by the factory must not assume Go or any Base tech."""
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            out = self._generate(self._kotlin_profile(), root)
            readme = (out / ".harness" / "README.md").read_text(encoding="utf-8")
            readme_lower = readme.lower()
            # Must not contain references to Go as the language
            self.assertNotIn("go engineering", readme_lower)
            self.assertNotIn("go engineer", readme_lower)
            self.assertNotIn("golang", readme_lower)
            # Must contain base_version as provenance
            self.assertIn("base", readme_lower)

    # ── 7. base_version remains as provenance ───────────────────────────

    def test_base_version_present_as_provenance(self):
        """base_version must be present in manifest and vault manifest."""
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            out = self._generate(self._kotlin_profile(), root, base_version="0.45.0")
            # manifest.json
            manifest = json.loads(
                (out / ".harness" / "manifest.json").read_text(encoding="utf-8")
            )
            self.assertEqual(manifest.get("base_harness_version"), "0.45.0")
            # vault-manifest.json
            vault_manifest = json.loads(
                (out / ".harness" / "vault" / "vault-manifest.json").read_text(encoding="utf-8")
            )
            self.assertEqual(vault_manifest.get("base_version"), "0.45.0")

    # ── 8. Policies and capabilities are still inherited ─────────────────

    def test_policies_still_available(self):
        """Policies must continue to be materialized in Dedicated Harness."""
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            out = self._generate(self._kotlin_profile(), root)
            harness_vault = out / ".harness" / "vault"
            notes = load_vault(harness_vault)
            # HITL, branching, identity, bootstrap policies must exist
            policy_note = notes.get("policies")
            self.assertIsNotNone(policy_note)
            policy_body = policy_note.body
            self.assertIn("HITL", policy_body)
            self.assertIn("Branching", policy_body)
            self.assertIn("Bootstrap", policy_body)

    # ── 9. Factory does not lose capabilities ───────────────────────────

    def test_factory_does_not_lose_capabilities(self):
        """All vault notes must still be materialized after removing Go identity."""
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            out = self._generate(self._kotlin_profile(), root)
            harness_vault = out / ".harness" / "vault"
            notes = load_vault(harness_vault)
            # Must have all essential notes
            expected = {"_index", "governance", "architecture", "agents",
                        "skills", "workflows", "policies", "tools"}
            found = set(notes.keys())
            missing = expected - found
            self.assertEqual(
                missing, set(),
                f"Missing vault notes: {missing}"
            )

    # ── Helpers ─────────────────────────────────────────────────────────

    def _generate(self, profile: dict, output_root: Path,
                  base_version: str = "0.1.0") -> Path:
        profile_path = output_root / "profile.json"
        project_out = output_root / "project"
        profile_path.write_text(json.dumps(profile), encoding="utf-8")
        result = generate_harness(profile_path, base_version, project_out)
        self.assertTrue(result["valid"])
        return project_out

    def _assert_no_go_identity(self, harness_root: Path) -> None:
        """Assert that a Dedicated Harness vault has no Go identity leakage."""
        vault_dir = harness_root / ".harness" / "vault"
        self.assertTrue(vault_dir.exists(), "Vault directory missing")
        notes = load_vault(vault_dir)
        for note_id, note in notes.items():
            # Check body for Go semantic dependency
            body_lower = note.body.lower()
            # "go " as a standalone word indicating Go language
            lines = note.body.splitlines()
            for i, line in enumerate(lines, 1):
                stripped = line.strip()
                # Skip: "governance", "goal", "google" etc.
                # Only flag "Go Engineer", "Go Engineering", "go-engineer"
                if "go engineer" in stripped.lower():
                    self.fail(
                        f"Note '{note_id}' ({note.filepath}:{i}) contains "
                        f"'Go Engineer': {stripped}"
                    )
                if "go engineering" in stripped.lower():
                    self.fail(
                        f"Note '{note_id}' ({note.filepath}:{i}) contains "
                        f"'Go Engineering': {stripped}"
                    )
                if "go-engineer" in stripped.lower():
                    self.fail(
                        f"Note '{note_id}' ({note.filepath}:{i}) contains "
                        f"'go-engineer': {stripped}"
                    )
        # README check
        readme = (harness_root / ".harness" / "README.md").read_text(encoding="utf-8")
        readme_lower = readme.lower()
        self.assertNotIn("go engineering", readme_lower)

    @staticmethod
    def _go_profile() -> dict:
        return {
            "schema_version": "1",
            "identity": {
                "proposed_product_name": "Go Service",
                "proposed_repository_name": "go-service",
                "short_description": "Go HTTP API",
                "problem_statement": "Need a Go API",
                "selected_architecture": "simple",
            },
            "domain": {"actors": [], "core_concepts": [], "entities": [], "business_rules": []},
            "technical": {"application_type": "HTTP API", "persistence": "none",
                          "interfaces": ["HTTP"], "external_dependencies": []},
            "constraints": [], "risks": [], "open_questions": [],
        }

    @staticmethod
    def _kotlin_profile() -> dict:
        return {
            "schema_version": "1",
            "identity": {
                "proposed_product_name": "Mobile App",
                "proposed_repository_name": "mobile-app",
                "short_description": "Android app",
                "problem_statement": "Need a mobile app",
                "selected_architecture": "mvc",
            },
            "domain": {"actors": [], "core_concepts": [], "entities": [], "business_rules": []},
            "technical": {"application_type": "Mobile", "persistence": "firebase",
                          "interfaces": ["Mobile UI"], "external_dependencies": []},
            "constraints": [], "risks": [], "open_questions": [],
        }

    @staticmethod
    def _python_profile() -> dict:
        return {
            "schema_version": "1",
            "identity": {
                "proposed_product_name": "Python Service",
                "proposed_repository_name": "py-service",
                "short_description": "Python API",
                "problem_statement": "Need a Python API",
                "selected_architecture": "layered",
            },
            "domain": {"actors": [], "core_concepts": [], "entities": [], "business_rules": []},
            "technical": {"application_type": "HTTP API", "persistence": "postgres",
                          "interfaces": ["HTTP"], "external_dependencies": []},
            "constraints": [], "risks": [], "open_questions": [],
        }


if __name__ == "__main__":
    unittest.main()