from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path


def load_json(path: Path) -> dict:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError("Project Profile must be a JSON object.")
    return data


def slugify(value: str) -> str:
    value = value.strip().lower()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    return value.strip("-") or "project"


def generate(project: Path, profile: Path, base_version: str, harness_version: str) -> dict:
    data = load_json(profile)
    identity = data["identity"]

    project_name = str(identity["proposed_product_name"])
    repository = str(identity["proposed_repository_name"])
    architecture = str(identity.get("selected_architecture", "pending"))

    target = project / ".harness"
    if target.exists():
        raise FileExistsError(f"{target} already exists; bootstrap will not overwrite it.")

    # Expected write set is .harness/**
    (target / "agents").mkdir(parents=True)
    (target / "skills").mkdir(parents=True)
    (target / "policies").mkdir(parents=True)
    (target / "workflows").mkdir(parents=True)
    (target / "tools").mkdir(parents=True)
    (target / "context").mkdir(parents=True)

    manifest = {
        "schema_version": "1",
        "harness_version": harness_version,
        "base_harness_version": base_version,
        "project_repository": repository,
        "architecture_profile": architecture,
        "selected_agents": [],
        "selected_skills": [],
        "selected_tools": [],
        "enabled_workflows": [],
    }

    (target / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

    (target / "README.md").write_text(
        f"""# {project_name} — Dedicated Harness

This harness is owned by the project repository.

## Base

- Base Harness: `{base_version}`
- Dedicated Harness: `{harness_version}`

## Project

- Product: {project_name}
- Repository: {repository}
- Architecture: {architecture}

## Generation

Generated by the Base Harness bootstrap process.

This generation does not commit or push changes automatically.
""",
        encoding="utf-8",
    )

    (target / "project-profile.md").write_text(
        f"""# Project Profile

## Identity

- Product: {project_name}
- Repository: {repository}

## Problem

{identity.get("problem_statement", "")}

## Description

{identity.get("short_description", "")}

## Architecture Profile at Bootstrap Time

`{architecture}`

This file is a generated project context artifact. The final architecture
must remain backed by the approved Architecture Decision.
""",
        encoding="utf-8",
    )

    (target / "architecture.md").write_text(
        f"""# Architecture

## Selected profile

`{architecture}`

## Status

Generated during Dedicated Harness bootstrap.

The project should link the final Architecture Decision / ADR here before
implementation begins.
""",
        encoding="utf-8",
    )

    return {
        "valid": True,
        "project": project_name,
        "repository": repository,
        "architecture": architecture,
        "base_harness_version": base_version,
        "dedicated_harness_version": harness_version,
        "output": str(target),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a Dedicated Harness in a real project.")
    parser.add_argument("--project", type=Path, required=True)
    parser.add_argument("--profile", type=Path, required=True)
    parser.add_argument("--base-version", required=True)
    parser.add_argument("--harness-version", default="0.1.0")
    parser.add_argument("--check-only", action="store_true")
    args = parser.parse_args()

    project = args.project.resolve()
    profile = args.profile.resolve()

    if not project.is_dir():
        print("Project root does not exist:", project)
        return 1
    if not (project / ".git").exists():
        print("Target is not a Git repository:", project)
        return 1
    if not profile.exists():
        print("Project Profile not found:", profile)
        return 1

    if args.check_only:
        print(json.dumps({
            "valid": True,
            "project": str(project),
            "profile": str(profile),
            "existing_harness": (project / ".harness").exists(),
        }, indent=2))
        return 0

    try:
        result = generate(project, profile, args.base_version, args.harness_version)
    except FileExistsError as exc:
        print(str(exc))
        return 1
    except Exception as exc:
        print("Generation failed:", exc)
        return 1

    print(json.dumps(result, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
